apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-project
spec:
  replicas: 2
  selector:
    matchLabels:
      app: go-project
  template:
    metadata:
      labels:
        app: go-project
    spec:
      containers:
        - name: go-project
          image: go-project:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 4001

---
apiVersion: v1
kind: Service
metadata:
  name: go-project-service
  labels:
    app: go-project
spec:
  selector:
    app: go-project
  ports:
    - name: websocket
      protocol: TCP
      port: 4001
      targetPort: 4001
  type: LoadBalancer